:PROPERTIES:
- org-mode configuration
#+Latex_class: els-article
#+LANGUAGE:  en
#+OPTIONS:   title:nil author:nil date:nil  H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+DRAWERS: LOGBOOK CLOCK HIDDEN PROPERTIES
#+STARTUP: overview
#+STARTUP: noindent
#+bibliography: Collection.bib
#+cite_export: csl 
#+LaTeX_HEADER: \usepackage{lineno}
#+LaTeX_HEADER: \linenumbers
#+LaTeX_HEADER: \usepackage{setspace}
#+LaTeX_HEADER: \onehalfspacing
#+LaTeX_HEADER: \authblk
#+LaTeX_HEADER: \usepackage{pdfpages}
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_header: \usepackage[final]{draftwatermark}
#+LaTeX_HEADER: \usepackage{gensymb}
#+LaTeX_HEADER: \usepackage{amsmath}
#+LaTeX_HEADER: \usepackage{chemfig}
#+LaTeX_HEADER: \setchemfig{atom style={scale=0.45}}
#+LaTeX_HEADER: \usepackage[]{mhchem}
:END:

#+BEGIN_EXPORT LaTeX
\begin{frontmatter}
\title{Imprecision Logic}
\author[NSO, UoO]{Matthew P.A. Henderson\corref{cor1}}
\ead{mhenderson@cheo.on.ca}
\author[NSO]{Michael Kowalski}
\author[NSO, UO]{Pranesh Chakraborty}
\address[NSO]{Newborn Screening Ontario, Children's Hospital of Eastern Ontario,Canada}
\address[UoO]{Department of Medicine, University of Ottawa,Canada} 
\cortext[cor1]{Corresponding author}
\end{frontmatter}
#+END_EXPORT

* Notes
** Focused Report
- The Focused Report category is intended for concise method
  evaluation contributions and succinct clinical manuscripts. All
  Focused Reports will undergo peer review.
- Submissions in this category should contain four sections:
  - Abstract (structured, no more than 250 words)
  - Introduction
  - Methods
  - Results
  - Discussion
  - An Impact Statement should appear after the abstract.
- They should be no more than 1,500 words in length with a maximum of
  20 references and a total of no more than two tables and
  figures. Figures and tables should not be multipart (i.e., Fig. 1A,
  1B, 1C, Part 1, Part 2). No more than 5 authors should be
  listed. Supplemental data are permitted for Focused Reports.

In some instances, editors may request that a submission of another article type to JALM be decreased to meet the requirements of a Focused Report.

* TODO Abstract (250 words)
- Introduction :: 
- Methods ::
- Results ::
- Conclusion :: 
* TODO Keywords
* TODO Introduction
- The probability that a laboratory will incorrectly assign a
  screen-positive or negative result owing to measurement error can be
  estimated from the area under the standardized normal distribution.

- The uncertainty of measurement approach uses an expansion factor
  of 2. This would result an \sim 2% probability of a false negative
  result (Table [[tab:sigma]]).
- The tolerance for a false negative first tier screening result at
  NSO is very low, therefore, the most appropriate expansion factor
  should be applied.

- Analytical drift due to factors such as calibrations and weather can
  result in periodic bias
- This should also be considered in determining impression logic

#+CAPTION[sigma]: Probability of a false negative screen due to imprecision
#+NAME: tab:sigma
| SD | probability of false negative | count
|----+-------------------------------+
|  1 |                     0.1586553 |
|  2 |                    0.02275013 |
|  3 |                   0.001349898 |
|  4 |                 3.167124ee-05 |
|  5 |                 2.866516ee-07 |
|  6 |                 9.865876ee-10 |


#+CAPTION[sigma]: Precison near screening thresholds
#+NAME: tab:precision
#+TBLNAME: datatable
| Analyte | Threshold | QC       | mean |  sd |
|---------+-----------+----------+------+-----|
| GALT    |       1.5 | G17069   |  1.6 | 0.2 |
| BIOT    |        27 | B170621  |   33 | 3.7 |
| TSH     |        15 | 659845-1 |   15 | 1.3 |

  
* TODO Material and Methods
* Results
#+begin_src R :session *R* :results values :exports results :tangle yes
      library("tidyverse")
      library("lubridate")
      library("magrittr")
      library("readxl")
      library("mcr")
      library("xts")
      library("TTR")
      library("RODBC")
      library("xtable")
      library("TSA")
      library("forecast")
      library("equate")
      library("moments")
      library(RColorBrewer)
      ## options(tibble.width = Inf)
      ##  options(tibble.print_max = Inf) 
      options(warn=-1) ## options(warn=0) to turn back on
      ## Suppress summarise info
      options(dplyr.summarise.inform = FALSE)
      ## options(tibble.width = Inf)
      ## options(tibble.print_max = Inf) 
      today <- as.Date(now())
      source("credentials.r")

      ## rescale a vector from 0 to 1
      rescale <- function(x){
	(x-min(x))/(max(x)-min(x))
      }

      '%!in%' <- function(x,y)!('%in%'(x,y))

    ### accept data, initial and confirm thresholds
    ### return the area of the probability density polygon 
      densarea <- function(dens, lower, upper) {
	xx <- dens$x
	yy <- dens$y
	dx <- xx[2] - xx[1] ## determine the increment
	C <- sum(yy) * dx ## total area should be very close to 1
	p.unscaled <- sum(yy[xx >= lower & xx <= upper]) * dx 
	round(p.unscaled/C, digits = 5) ## scaled probablity
      }


    ## accept data, confirmation threshold, sd at the threshold, factor expansion factor
    ## return
      denssamples <- function(data, confirm, sd, factor , direction = "left", samples = 145000) {
	  dens <- density(data)
	  if (direction == "left") {
	    ## calculate area between initial and confirm thresholds
	    # x value nearest the confirm threshold
	    lower <- dens$x[min(which(dens$x >= confirm))]
	    # initial threshold based on the sd and ef
	    initial <- confirm + (factor * sd) 
	    # x value nearest the initial threshold
	    upper <- dens$x[max(which(dens$x <= initial))]
	    # x value 6 sd above the confirm threshold
	    six <- dens$x[max(which(dens$x <= (confirm + (6 * sd))))]
	    # area of the probability density polygon between the initial and 6 sd above
	    totalarea <- densarea(dens, lower, six)
	  } else {
	    ## right sided threshold
	    upper <- dens$x[max(which(dens$x <= confirm))]
	    initial <- confirm - (sds * sd)
	    lower <- dens$x[min(which(dens$x >= initial))]
	    six <- dens$x[min(which(dens$x >= (confirm - (6 * sd))))]
	    totalarea <- densarea(dens, six, upper)
	  }
	  grey_area <- densarea(dens, lower, upper)
	  grey_area_samples <- grey_area * samples
	  #uncertain <- (totalarea * samples) - confirmed
	  list(factor,lower, upper, grey_area_samples)
	}

  
    ### accept data, initial and confirm thresholds
    ### return a density plot polygon area calculated
    thresholdplot <- function(data, initial, confirm,  units) {
	dens <- density(data)
	plot(dens, xlab = units, col = "grey", main = "")
	polygon(dens, col= "grey", border = NA)
	abline(v = initial , col = "black", lty = 2)
	abline(v = confirm , col = "black" )
	with(dens, polygon(x=c(initial, initial, x[x <= initial]), y=c(0, y[x <= initial], y[x=initial]),col = "deepskyblue", border = "deepskyblue"))
	with(dens, polygon(x=c(confirm, confirm, x[x <= confirm]), y=c(0, y[x <=confirm], y[x=confirm] ), col="darkred", border = "darkred"))
	initial_area <- densarea(dens, lower = min(data), upper = initial)
	confirm_area <- densarea(dens, lower = min(data), upper = confirm)
	legend("topright",
	       legend = c(paste0("Initial: ", initial),
			  paste0(round(initial_area*100, digits = 2),"%"),
			  paste0("Confirm: ", confirm),
			  paste0(round(confirm_area*100, digits = 2),"%")),
	       bty = "n",
	       col = c("black", "deepskyblue",
		       "black", "darkred"),
	       lty = c(2, NA, 1, NA),
	       pch = c(NA, 15, NA, 15))
      }

#+end_src

#+RESULTS:


#+begin_src R :session *R* :results values :exports results :tangle yes :cache no
  galtquery <- "select s.spcextcode1 as accession,
	   a.ansTimeMeasured as measured_time,
	   s.spcExtcode2 as form,
	   sd.sd2GestationAge as ga,
	   sd.sd2Weight as bw,
	   sd.sd2AgeAtCollection as aoc,
	   a.ansvalueplain as result,
	   va.ResultCode as result_code
	   from (select s.specimenid, a.testid, max(answerix) as answerindex
	   from Answer a inner join specimen s on s.SpecimenID = a.SpecimenID
	   where a.TestId = 13 
	   and a.ansStatus = 110
	   and s.spcextcode1 like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
	   and substring(s.spcextcode1,1,8) between '20180000' and '20190000'
	   and substring(s.spcextcode1,9,1) not in ('4', '7', '8')
	   group by s.specimenid, a.TestId) a1
	   inner join answer a on a1.SpecimenID = a.SpecimenID and a1.AnswerIndex = a.AnswerIX and a1.TestId = a.TestId
	   inner join specimen s on a1.specimenid = s.specimenid
	   inner join vw_Answers va on s.spcExtcode1 = va.AccessionNumber and a.TestId = va.TestID
	   inner join specimendetail2 sd on sd.SpecimenId = va.SpecimenID
	   order by s.spcextcode1"
  ## galtdata <- with_con(galtquery)
  ## write.csv(galtdata, file= paste0("./data/galt_data_", today, ".csv"))
  galtdata <- read.csv("./data/galt_data_2022-04-07.csv", stringsAsFactors = FALSE)
  galtdata$measured_time  <- ymd_hms(galtdata$measured_time)
  galtdata <- na.omit(galtdata)
#+end_src


#+begin_src R :session *R* :results output latex :exports results :tangle yes
    ## initialize the dataframe
      galtarea <- data.frame(factor = double(),
			     confirm = double(),
			     initial = double(),
  #			   grey_area = double(),
			     grey_samples = double(),
			     stringsAsFactors = FALSE)

    ## populate the dataframe
    for (i in 0:6) {
      galtarea[i+1,] <- denssamples(galtfilter$result, 1.5, 0.2, i, direction = "left")
    }

    galtarea %>%
      stargazer(summary = FALSE,
		title = "Uncertainty of Measurement Based Initial Screening Thresholds with Predicted Repeat Samples Population Data",
		digits = 1)
#+end_src

#+RESULTS:
#+begin_export latex

% Table created by stargazer v.5.2.2 by Marek Hlavac, Harvard University. E-mail: hlavac at fas.harvard.edu
% Date and time: Thu, Apr 14, 2022 - 05:28:41 PM
\begin{table}[!htbp] \centering 
  \caption{Uncertainty of Measurement Based Initial Screening Thresholds with Predicted Repeat Samples Population Data} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}} ccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & factor & confirm & initial & grey\_samples \\ 
\hline \\[-1.8ex] 
1 & $0$ & $1.5$ & $1.5$ & $0$ \\ 
2 & $1$ & $1.5$ & $1.7$ & $10.1$ \\ 
3 & $2$ & $1.5$ & $1.9$ & $24.7$ \\ 
4 & $3$ & $1.5$ & $2.1$ & $52.2$ \\ 
5 & $4$ & $1.5$ & $2.3$ & $94.2$ \\ 
6 & $5$ & $1.5$ & $2.5$ & $156.6$ \\ 
7 & $6$ & $1.5$ & $2.7$ & $234.9$ \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}
#+end_export


#+begin_src R :session *R* :results output graphics file :file ./figures/galtthresholds.pdf :exports results :tangle yes
    dens <- density(galtfilter$result)
    threshold  <- 1.5
    borderline <- 3.0
    umsd <- 0.2 ##SD at postive threshold
    theight  <- max(dens$y[which(dens$x <= threshold)])
    bheight  <- max(dens$y[which(dens$x <= borderline)])
  #  quantiles <- quantile(galtdata$result, c(0.025, 0.975))
    start  <- threshold - (6*umsd)
    stop <- threshold + (6*umsd)
    x2 <- seq(start,stop,0.01)
    y2 <- theight*rescale(dnorm(x2,threshold,umsd))
    ##rescale(dnorm(x2,pthreshold,0.3))
    ## create indices for half of the UM distribution
    halfx2 <- seq(threshold,stop,0.01) 
    #y1alongx2 <- y1[which(x == threshold):which(x == stop)]
    #halfy2 <- y2[which(x2==threshold):which(x2==stop)]
    halfy2 <- y2[121:length(y2)]
    ##miny <- pmin(halfy2, y1alongx2)

    plot(x= 0:1.5*borderline, y = 0:1.5*bheight, type = "n",
	 xlab = "U/g Hb",
	 ylab = "density")

    points(dens,type="l",bty="L")
    abline(v = threshold, col = "red" , lty = 1)
    abline(v = borderline, col = "blue", lty = 1) 
    abline(v = stop, col = "black", lty = 2 )
    ## segments(x0=borderline, y0=0,x1 = borderline, y1=bheight,col="blue", lty = 2 )
    ## segments(x0=threshold, y0=0,x1 = threshold, y1=theight,col="red", lty = 2 )
    points(x2,y2,type="l",col="red")

    ## create a vector of zeros
    zeros <- rep(0,length(halfx2))

    polygon(c(halfx2,rev(halfx2)),c(halfy2,zeros), border = NA, col="red")
    area <- 0.01 * sum(halfy2)
    samples <- round(area *145000, digits = 0)
    mtext(text= paste("Annual results in red area:",samples), side = 3)
    legend("topleft",legend = c("threshold", "borderline", expression(paste("6", sigma))),
	   col = c("red", "blue", "black") ,
	   lty = c("solid","solid", "dashed"))

#+end_src

#+RESULTS:
[[file:./figures/galtthresholds.pdf]]

* TODO Discussion
* TODO Conclusions

* Acknowledgments
Funding: None.
* References
#+print_bibliography:

